/********************************************************
* Name: RESTTradeItemsResponseHandler
* Created By: Vasu
* Date: 19-03-2017
* Description: Response Handler class to handle responses
*              from Retrieve Trade Items REST API
*********************************************************/
global class RESTTradeItemsResponseHandler extends RESTResponseHandlerBase {
  // custom Data Property
  public List<RESTTradeItemsWrapper> Data;
}