/* =====================================================================================
Type:       Test class
Purpose:    Test cases for homeRepPersonDetailAURA
========================================================================================*/
@isTest
private class homeRepPersonDetailAURATest{
    static testMethod void homeRepPersonDetailAURAAllTest() {
        homeRepPersonDetailAURA.getContactId();        
    }
}