/********************************************************
* Name: RESTRepairItemsResponseHandler
* Created By: Vasu
* Date: 19-03-2017
* Description: Response Handler class to handle responses
*              from Retrieve Trade List REST API
*********************************************************/
global class RESTRepairItemsResponseHandler extends RESTResponseHandlerBase {
  // custom Data Property
  public RESTClaimWrapper Data;
}