/************************************************************************************************************
Name: TradePortalSharingWrapper
=============================================================================================================
Purpose: Apex Wrapper class to hold workorder and its Account details.
===============================================================================================================
History
-----------
VERSION    AUTHOR           DATE             DETAIL        DESCRIPTION
1.0        Vasu             22/06/2018       Created       Home Repair
*************************************************************************************************************/

public class TradePortalSharingWrapper{    
    public ServiceAppointment serviceAppointment; 
    public String accountId;
    public String oldAccountId; 
    public String updateType;               
}