/********************************************************
* Name: RESTReportItemWrapper
* Created By: Mathew Jose
* Date: 23rd Feb 2018
* Description: REST API Wrapper Class for Sections
*              within an Inspection
*********************************************************/ 

global class RESTReportItemWrapper {

	//Report Item fields
	public String ItemId {get; set;} 
	public String Type {get; set;}  
	public String ItemDescription {get; set;} 
	public String ItemText {get; set;} 
	public String Name {get; set;} 


}