/********************************************************
* Name: RESTReportItemResponseHandler
* Created By: Mathew Jose
* Date: 23rd Feb 2018
* Description: Response Handler class to handle responses
*              from Retrieve ReportItems REST API
*********************************************************/
global class RESTReportItemResponseHandler extends RESTResponseHandlerBase {
  // custom Data Property
  public RESTReportItemsList Data;  
}